# Generated by Django 2.2.3 on 2019-09-22 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190922_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user4personels',
            name='baslama_tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
