# Generated by Django 2.2.3 on 2019-09-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190922_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user4personels',
            options={'verbose_name': 'Personel', 'verbose_name_plural': 'Personeller'},
        ),
    ]
