# Generated by Django 2.2.3 on 2019-09-22 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='proje_arsiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_kod', models.IntegerField()),
                ('aciklama', models.CharField(max_length=100)),
                ('aciklama_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='proje_durum',
            fields=[
                ('proje_durum', models.IntegerField(primary_key=True, serialize=False)),
                ('aciklama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='proje_status',
            fields=[
                ('proje_status_kod', models.IntegerField(primary_key=True, serialize=False)),
                ('aciklama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='proje_tip',
            fields=[
                ('proje_tip', models.IntegerField(primary_key=True, serialize=False)),
                ('aciklama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('proje_kod', models.IntegerField(primary_key=True, serialize=False, verbose_name='Proje Kodu')),
                ('proje_adi', models.CharField(max_length=140, verbose_name='Proje Adı')),
                ('baslama_tarihi', models.DateTimeField(verbose_name='Başlama Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('proje_calisanlar_no', models.TextField(blank=True, null=True, verbose_name='Proje Çalışanlarının Numaraları')),
                ('aciklama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Açıklama')),
                ('proje_durumu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_item.proje_durum', verbose_name='Proje Durumu')),
                ('proje_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_item.proje_status', verbose_name='Proje Status')),
                ('proje_teknik_yonetici_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Teknik Yönetici No')),
                ('proje_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_item.proje_tip', verbose_name='Proje Tipi')),
                ('proje_yoneticisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Yöneticisi')),
            ],
        ),
        migrations.CreateModel(
            name='personel_yetkilendirme',
            fields=[
                ('yetki_kod', models.IntegerField(unique=True)),
                ('baslanma_tarih', models.DateTimeField()),
                ('bitis_tarih', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personel_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Personel No')),
                ('proje_kod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_item.Proje', verbose_name='Proje Kod')),
            ],
        ),
    ]
