# Generated by Django 2.2.3 on 2019-09-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personel_yetkilendirme',
            fields=[
                ('personel_no', models.IntegerField()),
                ('proje_kod', models.IntegerField()),
                ('yetki_kod', models.IntegerField()),
                ('baslanma_tarih', models.DateTimeField()),
                ('bitis_tarih', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_kod', models.IntegerField()),
                ('proje_adi', models.CharField(max_length=140, verbose_name='proje adı')),
                ('baslama_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('proje_yoneticisi', models.IntegerField()),
                ('proje_teknik_yonetici_no', models.IntegerField()),
                ('proje_calisanlar_no', models.TextField(default=False)),
                ('aciklama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='proje_durum',
            fields=[
                ('proje_durum', models.IntegerField()),
                ('aciklama', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='proje_status',
            fields=[
                ('proje_status_kod', models.IntegerField()),
                ('aciklama', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='proje_tip',
            fields=[
                ('proje_tip', models.IntegerField()),
                ('aciklama', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
