# Generated by Django 2.2.3 on 2019-09-24 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0002_auto_20190924_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='proje_yoneticisi',
            field=models.ForeignKey(blank='Veri yok', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Yöneticisi'),
        ),
    ]
