# Generated by Django 2.2.3 on 2019-09-24 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0003_auto_20190924_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proje_tip',
            options={'verbose_name': 'Proje Tipi', 'verbose_name_plural': 'Proje Tipleri'},
        ),
        migrations.AlterField(
            model_name='proje',
            name='proje_yoneticisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Yöneticisi'),
        ),
    ]
