# Generated by Django 2.2.3 on 2019-09-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0004_auto_20190924_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personel_yetkilendirme',
            options={'verbose_name': 'Proje Yetkilendirme', 'verbose_name_plural': 'Proje Yetkilendirme'},
        ),
        migrations.AlterModelOptions(
            name='proje',
            options={'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='proje_arsiv',
            options={'verbose_name': 'Proje Arsiv', 'verbose_name_plural': 'Proje Arsiv'},
        ),
        migrations.AlterModelOptions(
            name='proje_durum',
            options={'verbose_name': 'Proje Durum', 'verbose_name_plural': 'Proje Durumları'},
        ),
        migrations.AlterModelOptions(
            name='proje_status',
            options={'verbose_name': 'Proje Status', 'verbose_name_plural': 'Proje Statusleri'},
        ),
    ]
