# Generated by Django 2.2.3 on 2019-09-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0005_auto_20190924_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proje_arsiv',
            options={'verbose_name': 'Proje Arşiv', 'verbose_name_plural': 'Proje Arşiv'},
        ),
    ]
