# Generated by Django 2.2.3 on 2019-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0009_auto_20190927_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='is_archive',
            field=models.IntegerField(choices=[(1, 'Arşilendi'), (2, 'Arşivlenmedi')], default=2, verbose_name='Arşiv durumu'),
        ),
    ]
