# Generated by Django 2.2.3 on 2019-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0010_auto_20190927_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='is_archive',
            field=models.IntegerField(choices=[(1, 'Arşilendi'), (0, 'Arşivlenmedi')], default=0, verbose_name='Arşiv durumu'),
        ),
    ]
