# Generated by Django 2.2.3 on 2019-10-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0011_auto_20190927_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje_arsiv',
            name='aciklama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
