# Generated by Django 2.2.3 on 2019-10-04 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0012_auto_20191004_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje_arsiv',
            name='aciklama_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
