# Generated by Django 2.2.3 on 2019-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0013_auto_20191004_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='aciklama_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Açıklama Tarihi'),
        ),
    ]
