# Generated by Django 2.2.3 on 2019-10-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0014_proje_aciklama_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='aciklama_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Açıklama Tarihi(Yalnızca arşivlerken ekleyin.)'),
        ),
    ]
