# Generated by Django 2.2.3 on 2019-10-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0015_auto_20191005_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proje_arsiv',
        ),
    ]
