# Generated by Django 2.2.3 on 2019-10-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0016_delete_proje_arsiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel_yetkilendirme',
            name='baslanma_tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel_yetkilendirme',
            name='bitis_tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
