# Generated by Django 2.2.3 on 2019-10-05 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_item', '0017_auto_20191005_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel_yetkilendirme',
            name='personel_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Personel No'),
        ),
        migrations.AlterField(
            model_name='personel_yetkilendirme',
            name='proje_kod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_item.Proje', verbose_name='Proje Kod'),
        ),
    ]
